### ISSUE TITLE
使用 组件时不能用自闭合标签

### ISSUE THREAD

**Issue by lsrKids** [huanguolin/ng-helper#9]
![1ad5d7e6-e480-421b-9750-e4edb5b4dc8e](https://github.com/user-attachments/assets/c6cde99a-d158-4acd-9e7c-f1b1b0ad6bb7)
上述代码会被处理成下述图
![709767c8-dc25-411c-b7cd-b7ead6a0fdcf](https://github.com/user-attachments/assets/53b86543-3cef-476e-9345-085386b00065)

**Comment by huanguolin** [comment]
一些补充信息：

[Void element](https://developer.mozilla.org/en-US/docs/Glossary/Void_element)

[反对 HTML 中自闭合标签的案例](https://jakearchibald.com/2023/against-self-closing-tags-in-html/)

[custom directives with self closing tags capture tag siblings](https://github.com/angular/angular.js/issues/1953)
